# Generated by Django 2.1.5 on 2020-04-05 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0004_auto_20200329_1857'),
    ]

    operations = [
        migrations.AddField(
            model_name='papers',
            name='num_assigned_user',
            field=models.IntegerField(default=0),
        ),
    ]
