# Generated by Django 2.1.5 on 2020-04-06 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0005_papers_num_assigned_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignedPapers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=120)),
                ('firstpaper', models.CharField(max_length=120)),
                ('secondpaper', models.CharField(max_length=120)),
                ('thirdpaper', models.CharField(max_length=120)),
            ],
        ),
    ]
