# Generated by Django 2.1.5 on 2020-04-06 02:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0006_assignedpapers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignedpapers',
            old_name='username',
            new_name='name',
        ),
    ]
