# Generated by Django 3.0.4 on 2020-04-09 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0006_papers_paper_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='papers',
            name='paper_status',
            field=models.CharField(choices=[('AC', 'Accepted'), ('RE', 'Rejected'), ('PN', 'Pending')], default='PN', max_length=2, null=True),
        ),
    ]
