# Generated by Django 3.0.4 on 2020-04-10 17:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('papers', '0008_auto_20200410_1107'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='papers',
            name='paper_reviewer',
        ),
        migrations.AddField(
            model_name='papers',
            name='paper_reviewer',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
