# Generated by Django 3.0.4 on 2020-04-10 19:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('papers', '0009_auto_20200410_1133'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='papers',
            name='paper_reviewer',
        ),
        migrations.AddField(
            model_name='papers',
            name='reviewer_1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paper_reviewed_by_1', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='papers',
            name='reviewer_2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paper_reviewed_by_2', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='papers',
            name='reviewer_3',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paper_reviewed_by_3', to=settings.AUTH_USER_MODEL),
        ),
    ]
