# Generated by Django 3.0.4 on 2020-04-11 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0010_auto_20200410_1348'),
        ('papers', '0007_auto_20200406_0214'),
    ]

    operations = [
    ]
