# Generated by Django 3.0.4 on 2020-04-11 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0011_merge_20200411_1300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='papers',
            name='paper_status',
            field=models.CharField(choices=[('Accepted', 'Accepted'), ('Rejected', 'Rejected'), ('Pending', 'Pending')], default='Pending', max_length=12, null=True),
        ),
    ]
