# Generated by Django 3.0.4 on 2020-04-11 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0012_auto_20200411_1301'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AssignedPapers',
        ),
        migrations.AddField(
            model_name='papers',
            name='preferred_reviewers',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
