# Generated by Django 3.0.5 on 2020-04-14 06:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('papers', '0013_auto_20200411_1504'),
    ]

    operations = [
        migrations.AddField(
            model_name='papers',
            name='paper_abstract',
            field=models.CharField(max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='papers',
            name='reviewer_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paper_reviewed_by_1', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='papers',
            name='reviewer_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paper_reviewed_by_2', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='papers',
            name='reviewer_3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paper_reviewed_by_3', to=settings.AUTH_USER_MODEL),
        ),
    ]
