# Generated by Django 3.0.5 on 2020-04-14 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0014_auto_20200414_0005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='papers',
            name='paper_abstract',
            field=models.FileField(null=True, upload_to='papers/'),
        ),
    ]
