# Generated by Django 3.0.5 on 2020-04-15 02:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0015_auto_20200414_0010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='papers',
            name='paper_abstract',
            field=models.FileField(upload_to='papers/'),
        ),
        migrations.AlterField(
            model_name='papers',
            name='paper_status',
            field=models.CharField(choices=[('Accepted', 'Accepted'), ('Rejected', 'Rejected'), ('Pending', 'Pending')], default='Pending', max_length=12),
        ),
        migrations.AlterField(
            model_name='papers',
            name='publication',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='papers.Journal'),
        ),
    ]
